export type EnginePoints = {
  "Race Order": number;
  "Pony ID": number;
  "Pony Name": string;
  Holder: string;
  Origins: string;
  Rune: string;
  Level: number;
  Experience: number;
  "Ability #1": string | null;
  "Ability #2": string | null;
  "Ability #3": string | null;
  Lane: string;
  "% votes": null;
  Indigestion: string;
  "Recent Indigestion": string;
  "Twitter Points": number;
  "Treat #1": string;
  "Treat #2": string;
  "Treat #3": string;
  "Treats Points 1": null;
  "Treat Points 2": null;
  "Treat Points 3": null;
  "Ability Treat Points": null;
  "Treats Points": number;
  "Event Points": null;
  "Attacks Suffered": null;
  "Attacks Protected": null;
  "Ability Rolls": null;
  "Ability Points": number;
  "Loot Points": number | null;
  "Training Points": number | null;
  "Morale Points": number | null;
  "Race Week Points": number;
  "Race Week Rank": number;
  "Race Week Championship Points": number;
  "Twitter Lane Experience": number;
  "Rank Experience": number;
  "Points Experience": number;
  "Race Week Experience": number;
};
