import React from 'react';
import Header from '../pages/Header/Header'
import Homes from '../pages/Home/'

import Question from '../pages/Questions/Question'
import Head from "next/head";

const Home = () => {
  return (
    <>
     <Head>
     <title>Heroes Of Cumberland</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/chicken.ico" />
      </Head>
      <body>
      <main className="main">
      <Header/>
      <Homes />
      <Question />
      </main>
      
      </body>
    </>
  );
};

export default Home;
